"""codigos de recuperacion de 6 digitos

Revision ID: 5cb4ddecc152
Revises: 1951a4ae8cf0
Create Date: 2026-09-10 21:31:31.584233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb4ddecc152'
down_revision: Union[str, Sequence[str], None] = '1951a4ae8cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM password_reset_tokens")
    op.add_column('password_reset_tokens', sa.Column('codigo_hash', sa.String(length=255), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('intentos', sa.Integer(), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('verificado', sa.Boolean(), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('session_token_hash', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_session_token_hash'), 'password_reset_tokens', ['session_token_hash'], unique=False)
    op.drop_column('password_reset_tokens', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_password_reset_tokens_session_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.drop_column('password_reset_tokens', 'session_token_hash')
    op.drop_column('password_reset_tokens', 'verificado')
    op.drop_column('password_reset_tokens', 'intentos')
    op.drop_column('password_reset_tokens', 'codigo_hash')
    # ### end Alembic commands ###
